-- MySQL Script generated by MySQL Workbench
-- Mon Mar 18 11:28:11 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Pizzeria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Pizzeria` DEFAULT CHARACTER SET utf8 ;
USE `Pizzeria` ;

-- -----------------------------------------------------
-- Table `Pizzeria`.`Localities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Localities` (
  `id_locality` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_locality`),
  UNIQUE INDEX `locality_id_UNIQUE` (`id_locality` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Provinces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Provinces` (
  `id_province` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `locality_id` INT NOT NULL,
  PRIMARY KEY (`id_province`),
  INDEX `locality_id_idx` (`locality_id` ASC) VISIBLE,
  UNIQUE INDEX `province_id_UNIQUE` (`id_province` ASC) VISIBLE,
  CONSTRAINT `locality_id2`
    FOREIGN KEY (`locality_id`)
    REFERENCES `Pizzeria`.`Localities` (`id_locality`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Customers` (
  `id_customer` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `postal_code` INT NOT NULL,
  `telephone` INT NOT NULL,
  `locality_id` INT NOT NULL,
  `province_id` INT NOT NULL,
  PRIMARY KEY (`id_customer`),
  INDEX `locality_id_idx` (`locality_id` ASC) VISIBLE,
  UNIQUE INDEX `customer_id_UNIQUE` (`id_customer` ASC) VISIBLE,
  CONSTRAINT `locality_id`
    FOREIGN KEY (`locality_id`)
    REFERENCES `Pizzeria`.`Localities` (`id_locality`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Products` (
  `id_product` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  `picture` BLOB NULL,
  `price` DECIMAL(11,5) NOT NULL,
  PRIMARY KEY (`id_product`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `description_UNIQUE` (`description` ASC) VISIBLE,
  UNIQUE INDEX `price_UNIQUE` (`price` ASC) VISIBLE,
  UNIQUE INDEX `products_id_UNIQUE` (`id_product` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Pizza_Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Pizza_Categories` (
  `id_category` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_category`),
  UNIQUE INDEX `category_id_UNIQUE` (`id_category` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Pizzas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Pizzas` (
  `id_pizza` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id_pizza`),
  INDEX `product_id_idx` (`product_id` ASC) VISIBLE,
  INDEX `category_id_idx` (`category_id` ASC) VISIBLE,
  UNIQUE INDEX `pizza_id_UNIQUE` (`id_pizza` ASC) VISIBLE,
  UNIQUE INDEX `product_id_UNIQUE` (`product_id` ASC) VISIBLE,
  UNIQUE INDEX `category_id_UNIQUE` (`category_id` ASC) VISIBLE,
  CONSTRAINT `product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `Pizzeria`.`Products` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `Pizzeria`.`Pizza_Categories` (`id_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Stores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Stores` (
  `id_stores` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(255) NOT NULL,
  `postal_code` INT NOT NULL,
  `locality_id` INT NOT NULL,
  `province_id` INT NOT NULL,
  PRIMARY KEY (`id_stores`),
  INDEX `locality_id_idx` (`locality_id` ASC) VISIBLE,
  UNIQUE INDEX `stores_id_UNIQUE` (`id_stores` ASC) VISIBLE,
  UNIQUE INDEX `province_id_UNIQUE` (`province_id` ASC) VISIBLE,
  UNIQUE INDEX `locality_id_UNIQUE` (`locality_id` ASC) VISIBLE,
  CONSTRAINT `locality_id3`
    FOREIGN KEY (`locality_id`)
    REFERENCES `Pizzeria`.`Localities` (`id_locality`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Orders` (
  `id_order` INT NOT NULL AUTO_INCREMENT,
  `order_datetime` DATETIME(6) NOT NULL,
  `is_delivery` ENUM('no_Delivery', 'delivery') NOT NULL,
  `total_price` DECIMAL(11,5) NOT NULL,
  `customer_id` INT NOT NULL,
  `store_id` INT NOT NULL,
  PRIMARY KEY (`id_order`),
  INDEX `customer_id_idx` (`customer_id` ASC) VISIBLE,
  INDEX `store_id_idx` (`store_id` ASC) VISIBLE,
  UNIQUE INDEX `order_id_UNIQUE` (`id_order` ASC) VISIBLE,
  UNIQUE INDEX `store_id_UNIQUE` (`store_id` ASC) VISIBLE,
  UNIQUE INDEX `customer_id_UNIQUE` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `Pizzeria`.`Customers` (`id_customer`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `store_id`
    FOREIGN KEY (`store_id`)
    REFERENCES `Pizzeria`.`Stores` (`id_stores`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Order_Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Order_Products` (
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  INDEX `order_id_idx` (`order_id` ASC) VISIBLE,
  INDEX `product_id_idx` (`product_id` ASC) VISIBLE,
  UNIQUE INDEX `order_id_UNIQUE` (`order_id` ASC) VISIBLE,
  UNIQUE INDEX `product_id_UNIQUE` (`product_id` ASC) VISIBLE,
  CONSTRAINT `order_id`
    FOREIGN KEY (`order_id`)
    REFERENCES `Pizzeria`.`Orders` (`id_order`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `product_id2`
    FOREIGN KEY (`product_id`)
    REFERENCES `Pizzeria`.`Products` (`id_product`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Sellers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Sellers` (
  `id_seller` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `nif` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(45) NOT NULL,
  `delivery_person` ENUM('cook', 'delivery_man') NOT NULL,
  `store_id` INT NOT NULL,
  PRIMARY KEY (`id_seller`),
  INDEX `store_id_idx` (`store_id` ASC) VISIBLE,
  UNIQUE INDEX `seller_id_UNIQUE` (`id_seller` ASC) VISIBLE,
  UNIQUE INDEX `store_id_UNIQUE` (`store_id` ASC) VISIBLE,
  CONSTRAINT `store_id2`
    FOREIGN KEY (`store_id`)
    REFERENCES `Pizzeria`.`Stores` (`id_stores`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Deliveries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Deliveries` (
  `id_delivery` INT NOT NULL AUTO_INCREMENT,
  `delivery_datetime` DATETIME(6) NOT NULL,
  `order_id` INT NOT NULL,
  `seller_id` INT NOT NULL,
  PRIMARY KEY (`id_delivery`),
  INDEX `order_id_idx` (`order_id` ASC) VISIBLE,
  INDEX `seller_id_idx` (`seller_id` ASC) VISIBLE,
  UNIQUE INDEX `delivery_id_UNIQUE` (`id_delivery` ASC) VISIBLE,
  UNIQUE INDEX `order_id_UNIQUE` (`order_id` ASC) VISIBLE,
  UNIQUE INDEX `seller_id_UNIQUE` (`seller_id` ASC) VISIBLE,
  CONSTRAINT `order_id2`
    FOREIGN KEY (`order_id`)
    REFERENCES `Pizzeria`.`Orders` (`id_order`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `seller_id`
    FOREIGN KEY (`seller_id`)
    REFERENCES `Pizzeria`.`Sellers` (`id_seller`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
