-- MySQL Script generated by MySQL Workbench
-- Tue Mar 12 10:27:31 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Optics
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Optics
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Optics` DEFAULT CHARACTER SET utf8 ;
USE `Optics` ;

-- -----------------------------------------------------
-- Table `Optics`.`Suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optics`.`Suppliers` (
  `id_supplier` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `number_street` INT NOT NULL,
  `floor` INT NULL,
  `door` INT NULL,
  `postal_code` INT NOT NULL,
  `telephone` INT NOT NULL,
  `fax` INT NULL,
  `nif` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_supplier`),
  UNIQUE INDEX `id_supplier_UNIQUE` (`id_supplier` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optics`.`Brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optics`.`Brands` (
  `id_brand` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_brand`),
  UNIQUE INDEX `id_brand_UNIQUE` (`id_brand` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optics`.`Glasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optics`.`Glasses` (
  `id_glass` INT NOT NULL AUTO_INCREMENT,
  `graduation` VARCHAR(45) NOT NULL,
  `material` VARCHAR(45) NOT NULL,
  `material_color` VARCHAR(45) NOT NULL,
  `glass_color` VARCHAR(45) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `supplier_id` INT NOT NULL,
  `brand_id` INT NOT NULL,
  PRIMARY KEY (`id_glass`),
  INDEX `providers_id_idx` (`supplier_id` ASC) VISIBLE,
  INDEX `brand_id_idx` (`brand_id` ASC) VISIBLE,
  UNIQUE INDEX `id_glass_UNIQUE` (`id_glass` ASC) VISIBLE,
  CONSTRAINT `supllier_id`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `Optics`.`Suppliers` (`id_supplier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `brand_id`
    FOREIGN KEY (`brand_id`)
    REFERENCES `Optics`.`Brands` (`id_brand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optics`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optics`.`Customers` (
  `id_customer` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `postal_code` INT NOT NULL,
  `telephone` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  `registration_date` DATETIME(6) NOT NULL,
  `recommended_by` INT NULL,
  PRIMARY KEY (`id_customer`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `recommended_by_idx` (`recommended_by` ASC) VISIBLE,
  UNIQUE INDEX `id_customer_UNIQUE` (`id_customer` ASC) VISIBLE,
  CONSTRAINT `recommended_by`
    FOREIGN KEY (`recommended_by`)
    REFERENCES `Optics`.`Customers` (`id_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optics`.`Sellers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optics`.`Sellers` (
  `id_seller` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_seller`),
  UNIQUE INDEX `id_seller_UNIQUE` (`id_seller` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optics`.`Sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optics`.`Sales` (
  `id_sale` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `seller_id` INT NOT NULL,
  `glass_id` INT NOT NULL,
  PRIMARY KEY (`id_sale`),
  INDEX `customer_id_idx` (`customer_id` ASC) VISIBLE,
  INDEX `seller_id_idx` (`seller_id` ASC) VISIBLE,
  INDEX `glass_id_idx` (`glass_id` ASC) VISIBLE,
  UNIQUE INDEX `id_sale_UNIQUE` (`id_sale` ASC) VISIBLE,
  CONSTRAINT `customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `Optics`.`Customers` (`id_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `seller_id`
    FOREIGN KEY (`seller_id`)
    REFERENCES `Optics`.`Sellers` (`id_seller`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `glass_id`
    FOREIGN KEY (`glass_id`)
    REFERENCES `Optics`.`Glasses` (`id_glass`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
